version: '2'
services:
  matomo:
    build: .
    volumes:
      - ${MATOMO_HOME}:/usr/src/piwik:cached
      - ./entrypoint.sh:/home/root/entrypoint.sh
      - ./environments/phps/php-$PHP_VERSION:/etc/my-php
    working_dir: /usr/src/piwik
    depends_on:
      - mariadb
      - mail
    ports:
      - "3000:3000"
    environment:
      - PHP_VERSION="$PHP_VERSION"
    command: php -S matomo:3000
    entrypoint: /home/root/entrypoint.sh
  mail:
    image: namshi/smtp
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mariadb:/var/lib/mysql:delegated
  trackerproxy:
    image: php:7-apache
    volumes:
      - ${MATOMO_TRACKER_PROXY_HOME}:/var/www/html/
    ports:
      - "3002:80"
    links:
      - matomo
  wordpress:
    image: wordpress
    ports:
      - "3001:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=pass
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
    links:
      - mariadb
      - trackerproxy
  redis:
    image: redis:3-alpine
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: matomo:3000
      SERVERNAME: matomo
    ports:
      - "4000:443"
