version: '2'
services:
  piwik:
    image: piwik
    restart: always
    volumes:
      - ../piwik:/usr/src/piwik
      - ./piwik.php.ini:/usr/local/etc/php/conf.d/piwik.php.ini
    working_dir: /usr/src/piwik
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    command: php -S piwik:3000
  mariadb:
    image: mariadb
    container_name: piwik-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mariadb:/var/lib/mysql
