version: '2'
services:
  piwik:
    build: .
    volumes:
      - ${PIWIK_HOME}:/usr/src/piwik
      - ./piwik.php.ini:/usr/local/etc/php/conf.d/piwik.php.ini
      - ./dev-entrypoint.sh:/usr/src/dev-entrypoint.sh
    working_dir: /usr/src/piwik
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    command: php -S piwik:3000
    entrypoint: /usr/src/dev-entrypoint.sh
  mariadb:
    image: mariadb
    container_name: piwik-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mariadb:/var/lib/mysql
